name: Test Suite

on: [push, pull_request]

jobs:
  build:
    name: build (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
        django-version: ['2.0', '2.1', '2.2', '3.0', '3.1', '3.2']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: py-${{ matrix.python-version }}-django-${{ matrix.django-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2

      - name: Install dependencies
        run: |
          poetry add django==${{ matrix.django-version }}
          poetry install

      - name: Tests
        run: poetry run scripts/test.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v1
